version: '2.2'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
  web: 
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/chat_system
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db