version: '3.1'
networks:
  elastic:
    driver: bridge

services:
  redis:
    image: 'redis'
    entrypoint: redis-server --appendonly yes
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    
  web: 
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - '.:/chat_system'
    ports:
      - "3000:3000"
    depends_on:
      - 'redis'
      - 'db'

  db:
    image: 'mysql:5.7'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root


  sidekiq:
    build: .
    volumes:
      - '.:/chat_system'
    depends_on:
      - 'db'
      - 'redis'
      - 'web'
    environment: 
      REDIS_URL: redis://redis:6379/0
    command: bundle exec sidekiq -C config/sidekiq.yml

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
      
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
    links:
      - es01

volumes:
  data01:
    driver: local
  data02:
    driver: local
  redis:
