#config/redis.yml
default:
  host: localhost
  port: 6379
development:
  db: 0
#  namespace: chat_system_dev
test:
  db: 1
#  namespace: chat_system_test
production:
  db: 2
  host: 192.168.1.100
#  namespace: chat_system_prod