#config/redis.yml
default:
  port: 6379
development:
  db: 0
#  namespace: chat_system_dev
test:
  db: 1
#  namespace: chat_system_test
production:
  db: 2
  port: 127.0.0.1
#  namespace: chat_system_prod